---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 40
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
